packages:
  - packages/package-0
  - packages/package-1
  - packages/package-2
  - packages/package-3
  - packages/package-4
  - packages/package-5
  - packages/package-6
  - packages/package-7
  - packages/package-8
  - packages/package-9
  - packages/package-10
  - packages/package-11
  - packages/package-12
  - packages/package-13
  - packages/package-14
  - packages/package-15
  - packages/package-16
  - packages/package-17
  - packages/package-18
  - packages/package-19
  - packages/package-20
  - packages/package-21
  - packages/package-22
  - packages/package-23
  - packages/package-24
  - packages/package-25
  - packages/package-26
  - packages/package-27
  - packages/package-28
  - packages/package-29
  - packages/package-30
  - packages/package-31
  - packages/package-32
  - packages/package-33
  - packages/package-34
  - packages/package-35
  - packages/package-36
  - packages/package-37
  - packages/package-38
  - packages/package-39
  - packages/package-40
  - packages/package-41
  - packages/package-42
  - packages/package-43
  - packages/package-44
  - packages/package-45
  - packages/package-46
  - packages/package-47
  - packages/package-48
  - packages/package-49
  - packages/package-50
  - packages/package-51
  - packages/package-52
  - packages/package-53
  - packages/package-54
  - packages/package-55
  - packages/package-56
  - packages/package-57
  - packages/package-58
  - packages/package-59
  - packages/package-60
  - packages/package-61
  - packages/package-62
  - packages/package-63
  - packages/package-64
  - packages/package-65
  - packages/package-66
  - packages/package-67
  - packages/package-68
  - packages/package-69
  - packages/package-70
  - packages/package-71
  - packages/package-72
  - packages/package-73
  - packages/package-74
  - packages/package-75
  - packages/package-76
  - packages/package-77
  - packages/package-78
  - packages/package-79
  - packages/package-80
  - packages/package-81
  - packages/package-82
  - packages/package-83
  - packages/package-84
  - packages/package-85
  - packages/package-86
  - packages/package-87
  - packages/package-88
  - packages/package-89
  - packages/package-90
  - packages/package-91
  - packages/package-92
  - packages/package-93
  - packages/package-94
  - packages/package-95
  - packages/package-96
  - packages/package-97
  - packages/package-98
  - packages/package-99